<?php
require_once __DIR__ . '/../config/config.php';
require_once __DIR__ . '/../config/database.php';

// Generate a fresh CSRF token for the frontend to use in its API requests
$csrfToken = cjcCsrfToken();
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CJC Clinic</title>
    
    <!-- CSRF token for use by fetch() calls in JavaScript -->
    <meta name="csrf-token" content="<?php echo cjcEscape($csrfToken); ?>">
    
    <!-- Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap" rel="stylesheet">
    
    <!-- Production CSS generated by Vite -->
    <link rel="stylesheet" href="/dist/css/app.css">
</head>
<body>
    <div id="app"></div>
    
    <!-- Production JS generated by Vite -->
    <script type="module" src="/dist/js/app.js"></script>
</body>
</html>
