<?php
require_once __DIR__ . '/backend/config/database.php';
try {
    $pdo = cjcDatabaseConnection();
    
    // Borrowings Table
    $pdo->exec("
    CREATE TABLE IF NOT EXISTS `borrowings` (
      `id` INT AUTO_INCREMENT PRIMARY KEY,
      `profile_id` INT NOT NULL,
      `purpose` VARCHAR(255) NOT NULL,
      `status` ENUM('pending', 'active', 'returned') DEFAULT 'pending',
      `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      `returned_at` TIMESTAMP NULL DEFAULT NULL,
      FOREIGN KEY (`profile_id`) REFERENCES `profiles`(`id`) ON DELETE CASCADE
    );
    ");

    // Borrowed Items Table
    $pdo->exec("
    CREATE TABLE IF NOT EXISTS `borrowed_items` (
      `id` INT AUTO_INCREMENT PRIMARY KEY,
      `borrowing_id` INT NOT NULL,
      `inventory_item_id` INT NOT NULL,
      `quantity` INT NOT NULL DEFAULT 1,
      `item_type` ENUM('equipment', 'supply') NOT NULL,
      `status` ENUM('borrowed', 'returned', 'dispensed') NOT NULL,
      FOREIGN KEY (`borrowing_id`) REFERENCES `borrowings`(`id`) ON DELETE CASCADE,
      FOREIGN KEY (`inventory_item_id`) REFERENCES `inventory_items`(`id`) ON DELETE CASCADE
    );
    ");

    // Settings Table
    $pdo->exec("
    CREATE TABLE IF NOT EXISTS `settings` (
      `setting_key` VARCHAR(50) PRIMARY KEY,
      `setting_value` TEXT NOT NULL
    );
    ");

    try { $pdo->exec("ALTER TABLE `profiles` ADD COLUMN `height` VARCHAR(20) DEFAULT NULL;"); } catch (Exception $e) {}
    try { $pdo->exec("ALTER TABLE `profiles` ADD COLUMN `weight` VARCHAR(20) DEFAULT NULL;"); } catch (Exception $e) {}
    try { $pdo->exec("ALTER TABLE `profiles` ADD COLUMN `mother_name` VARCHAR(100) DEFAULT NULL;"); } catch (Exception $e) {}
    try { $pdo->exec("ALTER TABLE `profiles` ADD COLUMN `father_name` VARCHAR(100) DEFAULT NULL;"); } catch (Exception $e) {}
    try { $pdo->exec("ALTER TABLE `appointments` ADD COLUMN `appointment_code` VARCHAR(50) DEFAULT NULL AFTER `id`;"); } catch (Exception $e) {}

    // Patient profile attachments (used by the Patient View modal)
    $pdo->exec("
    CREATE TABLE IF NOT EXISTS `profile_attachments` (
      `id` INT AUTO_INCREMENT PRIMARY KEY,
      `profile_id` INT NOT NULL,
      `filename` VARCHAR(255) NOT NULL,
      `file_url` VARCHAR(500) NOT NULL,
      `uploaded_by` VARCHAR(100) DEFAULT NULL,
      `extracted_text` LONGTEXT DEFAULT NULL,
      `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (`profile_id`) REFERENCES `profiles`(`id`) ON DELETE CASCADE
    );
    ");

    // Remove the canned findings generated by the old demo-only OCR script.
    // Real OCR never fabricates a clinical result when an image cannot be read.
    $pdo->exec("
        UPDATE `profile_attachments`
        SET `extracted_text` = NULL
        WHERE `extracted_text` LIKE 'HEMATOLOGY REPORT (COMPLETE BLOOD COUNT)%'
           OR `extracted_text` LIKE 'RADIOLOGY REPORT - CHEST X-RAY (PA VIEW)%'
    ");

    // Retry attachments that were uploaded while the OCR engine was unavailable.
    $ocrScript = realpath(__DIR__ . '/backend/scripts/ocr_parser.py');
    $uploadDir = realpath(CJC_UPLOAD_DIR);
    $pythonExecutable = getenv('CJC_PYTHON_EXECUTABLE') ?: 'python';
    if (DIRECTORY_SEPARATOR === '\\' && $pythonExecutable === 'python') {
        $localAppData = getenv('LOCALAPPDATA');
        $preferredPython = $localAppData ? glob($localAppData . '\\Programs\\Python\\Python313\\python.exe') : [];
        if (!empty($preferredPython)) {
            $pythonExecutable = $preferredPython[0];
        }
    }

    $recoveredExtracts = 0;
    if ($ocrScript && $uploadDir) {
        $attachments = $pdo->query("SELECT id, file_url FROM profile_attachments WHERE extracted_text IS NULL")->fetchAll(PDO::FETCH_ASSOC);
        $updateExtract = $pdo->prepare("UPDATE profile_attachments SET extracted_text = :text WHERE id = :id");

        foreach ($attachments as $attachment) {
            parse_str(parse_url($attachment['file_url'], PHP_URL_QUERY) ?? '', $query);
            $storedFile = basename($query['file'] ?? '');
            $filePath = realpath($uploadDir . DIRECTORY_SEPARATOR . $storedFile);
            if (!$storedFile || !$filePath || !str_starts_with($filePath, $uploadDir . DIRECTORY_SEPARATOR)) {
                continue;
            }

            $output = [];
            $returnCode = 0;
            $command = escapeshellarg($pythonExecutable) . ' ' . escapeshellarg($ocrScript) . ' ' . escapeshellarg($filePath) . ' 2>&1';
            exec($command, $output, $returnCode);
            $ocr = $returnCode === 0 ? json_decode(implode("\n", $output), true) : null;
            if (!empty($ocr['success']) && !empty($ocr['text'])) {
                $updateExtract->execute(['text' => $ocr['text'], 'id' => $attachment['id']]);
                $recoveredExtracts++;
            }
        }
    }

    try {
        $pdo->exec("ALTER TABLE `profiles` MODIFY COLUMN `profile_type` ENUM('student', 'employee', 'guest') NOT NULL DEFAULT 'student'");
    } catch (PDOException $e) {
        // Ignore error
    }

    try {
        $pdo->exec("ALTER TABLE `borrowings` ADD COLUMN `booking_code` VARCHAR(20) DEFAULT NULL UNIQUE AFTER `id`");
    } catch (PDOException $e) {
        // Ignore error
    }

    try {
        $pdo->exec("ALTER TABLE `borrowings` ADD COLUMN `expected_return_date` DATETIME DEFAULT NULL AFTER `purpose`");
    } catch (PDOException $e) {
        // Ignore error
    }

    try {
        $pdo->exec("ALTER TABLE `borrowings` ADD COLUMN `released_by` INT DEFAULT NULL AFTER `expected_return_date`");
    } catch (PDOException $e) {
        // Ignore error
    }

    // borrowed_items: track whether equipment stock was reserved
    try {
        $pdo->exec("ALTER TABLE `borrowed_items` ADD COLUMN `stock_reserved` TINYINT(1) NOT NULL DEFAULT 0 AFTER `status`");
    } catch (PDOException $e) {
        // Ignore error
    }

    // Return reconciliation table — tracks per-item return details
    $pdo->exec("
    CREATE TABLE IF NOT EXISTS `borrowed_item_returns` (
      `id` INT AUTO_INCREMENT PRIMARY KEY,
      `borrowed_item_id` INT NOT NULL,
      `quantity_returned` INT NOT NULL DEFAULT 0,
      `quantity_consumed` INT NOT NULL DEFAULT 0,
      `notes` TEXT DEFAULT NULL,
      `processed_by` INT DEFAULT NULL,
      `returned_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (`borrowed_item_id`) REFERENCES `borrowed_items`(`id`) ON DELETE CASCADE,
      FOREIGN KEY (`processed_by`) REFERENCES `users`(`id`) ON DELETE SET NULL
    );
    ");

    try {
        $pdo->exec("ALTER TABLE `inventory_items` 
            ADD COLUMN `date_acquired` DATE DEFAULT NULL,
            ADD COLUMN `date_purchased` DATE DEFAULT NULL,
            ADD COLUMN `last_calibrated` DATE DEFAULT NULL,
            ADD COLUMN `calibration_due` DATE DEFAULT NULL,
            ADD COLUMN `calibration_notes` TEXT DEFAULT NULL
        ");
    } catch (PDOException $e) {
        // Ignore error
    }

    // Equipment Calibrations Table
    $pdo->exec("
    CREATE TABLE IF NOT EXISTS `equipment_calibrations` (
      `id` INT AUTO_INCREMENT PRIMARY KEY,
      `item_id` INT NOT NULL,
      `batch_id` INT DEFAULT NULL,
      `cert_type` ENUM('external_upload', 'internal_generated') NOT NULL DEFAULT 'external_upload',
      `calibrated_by` VARCHAR(150) DEFAULT NULL,
      `cert_number` VARCHAR(100) DEFAULT NULL,
      `calibration_date` DATE DEFAULT NULL,
      `due_date` DATE DEFAULT NULL,
      `file_url` VARCHAR(500) DEFAULT NULL,
      `filename` VARCHAR(255) DEFAULT NULL,
      `uploaded_by` VARCHAR(100) DEFAULT NULL,
      `notes` TEXT DEFAULT NULL,
      `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (`item_id`) REFERENCES `inventory_items`(`id`) ON DELETE CASCADE
    );
    ");

    try { $pdo->exec("ALTER TABLE `equipment_calibrations` ADD COLUMN `batch_id` INT DEFAULT NULL AFTER `item_id`;"); } catch (Exception $e) {}
    try {
        $pdo->exec("ALTER TABLE `inventory_batches` 
            ADD COLUMN `last_calibrated` DATE DEFAULT NULL,
            ADD COLUMN `calibration_due` DATE DEFAULT NULL,
            ADD COLUMN `calibration_notes` TEXT DEFAULT NULL
        ");
    } catch (Exception $e) {}

    echo "Tables created/updated successfully. Recovered {$recoveredExtracts} OCR extract(s).\n";


} catch (Exception $e) {
    echo "Error: " . $e->getMessage() . "\n";
}
