<?php
require_once __DIR__ . '/backend/config/database.php';
try {
    $pdo = cjcDatabaseConnection();
    
    // Borrowings Table
    $pdo->exec("
    CREATE TABLE IF NOT EXISTS `borrowings` (
      `id` INT AUTO_INCREMENT PRIMARY KEY,
      `profile_id` INT NOT NULL,
      `purpose` VARCHAR(255) NOT NULL,
      `status` ENUM('pending', 'active', 'returned') DEFAULT 'pending',
      `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      `returned_at` TIMESTAMP NULL DEFAULT NULL,
      FOREIGN KEY (`profile_id`) REFERENCES `profiles`(`id`) ON DELETE CASCADE
    );
    ");

    // Borrowed Items Table
    $pdo->exec("
    CREATE TABLE IF NOT EXISTS `borrowed_items` (
      `id` INT AUTO_INCREMENT PRIMARY KEY,
      `borrowing_id` INT NOT NULL,
      `inventory_item_id` INT NOT NULL,
      `quantity` INT NOT NULL DEFAULT 1,
      `item_type` ENUM('equipment', 'supply') NOT NULL,
      `status` ENUM('borrowed', 'returned', 'dispensed') NOT NULL,
      FOREIGN KEY (`borrowing_id`) REFERENCES `borrowings`(`id`) ON DELETE CASCADE,
      FOREIGN KEY (`inventory_item_id`) REFERENCES `inventory_items`(`id`) ON DELETE CASCADE
    );
    ");

    // Settings Table
    $pdo->exec("
    CREATE TABLE IF NOT EXISTS `settings` (
      `setting_key` VARCHAR(50) PRIMARY KEY,
      `setting_value` TEXT NOT NULL
    );
    ");

    // Patient profile attachments (used by the Patient View modal)
    $pdo->exec("
    CREATE TABLE IF NOT EXISTS `profile_attachments` (
      `id` INT AUTO_INCREMENT PRIMARY KEY,
      `profile_id` INT NOT NULL,
      `filename` VARCHAR(255) NOT NULL,
      `file_url` VARCHAR(500) NOT NULL,
      `uploaded_by` VARCHAR(100) DEFAULT NULL,
      `extracted_text` LONGTEXT DEFAULT NULL,
      `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (`profile_id`) REFERENCES `profiles`(`id`) ON DELETE CASCADE
    );
    ");

    // Remove the canned findings generated by the old demo-only OCR script.
    // Real OCR never fabricates a clinical result when an image cannot be read.
    $pdo->exec("
        UPDATE `profile_attachments`
        SET `extracted_text` = NULL
        WHERE `extracted_text` LIKE 'HEMATOLOGY REPORT (COMPLETE BLOOD COUNT)%'
           OR `extracted_text` LIKE 'RADIOLOGY REPORT - CHEST X-RAY (PA VIEW)%'
    ");

    // Retry attachments that were uploaded while the OCR engine was unavailable.
    $ocrScript = realpath(__DIR__ . '/backend/scripts/ocr_parser.py');
    $uploadDir = realpath(CJC_UPLOAD_DIR);
    $pythonExecutable = getenv('CJC_PYTHON_EXECUTABLE') ?: 'python';
    if (DIRECTORY_SEPARATOR === '\\' && $pythonExecutable === 'python') {
        $localAppData = getenv('LOCALAPPDATA');
        $preferredPython = $localAppData ? glob($localAppData . '\\Programs\\Python\\Python313\\python.exe') : [];
        if (!empty($preferredPython)) {
            $pythonExecutable = $preferredPython[0];
        }
    }

    $recoveredExtracts = 0;
    if ($ocrScript && $uploadDir) {
        $attachments = $pdo->query("SELECT id, file_url FROM profile_attachments WHERE extracted_text IS NULL")->fetchAll(PDO::FETCH_ASSOC);
        $updateExtract = $pdo->prepare("UPDATE profile_attachments SET extracted_text = :text WHERE id = :id");

        foreach ($attachments as $attachment) {
            parse_str(parse_url($attachment['file_url'], PHP_URL_QUERY) ?? '', $query);
            $storedFile = basename($query['file'] ?? '');
            $filePath = realpath($uploadDir . DIRECTORY_SEPARATOR . $storedFile);
            if (!$storedFile || !$filePath || !str_starts_with($filePath, $uploadDir . DIRECTORY_SEPARATOR)) {
                continue;
            }

            $output = [];
            $returnCode = 0;
            $command = escapeshellarg($pythonExecutable) . ' ' . escapeshellarg($ocrScript) . ' ' . escapeshellarg($filePath) . ' 2>&1';
            exec($command, $output, $returnCode);
            $ocr = $returnCode === 0 ? json_decode(implode("\n", $output), true) : null;
            if (!empty($ocr['success']) && !empty($ocr['text'])) {
                $updateExtract->execute(['text' => $ocr['text'], 'id' => $attachment['id']]);
                $recoveredExtracts++;
            }
        }
    }

    try {
        $pdo->exec("ALTER TABLE `inventory_items` ADD COLUMN `formulation` VARCHAR(100) DEFAULT NULL AFTER `dosage`");
    } catch (PDOException $e) {
        // Ignore if column already exists
    }
    
    echo "Tables created/updated successfully. Recovered {$recoveredExtracts} OCR extract(s).\n";
} catch (Exception $e) {
    echo "Error: " . $e->getMessage() . "\n";
}
